on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/LICENSE'
      - '**/*.md'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: uhobeike/mkdocs-serve
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: mkdocs gh-deploy --force
