on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/LICENSE'
      - '**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/uhobeike/mkdocs-serve:latest

    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: mkdocs gh-deploy --force
